### ISSUE TITLE
Advanced CMS features tracking issue

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-data-rust#622]
This is a tracking issue for (advanced) headless CMS features that I think Atomic-Server will need. Most of these are encountered in tenders and competitors. 

- [x] Adjust menu structure
- [x] Create and edit articles / pages
- [x] Versioning
- [x] Rights management
- [x] Full-text search
- [x] Filters & sorting
- [ ] Aggregation counts for facets
- [ ] Groups for rights
- [ ] Custom process flows (including drafts, reviews, pipelines)
- [ ] Copyright notice management (e.g. in files / images)
- [ ] Linkchecker. Could be a plugin that checks all markdown fields for links, fetches these, creates warnings if they have issues. Maybe it sets a `dead-links` property on the resource, which in turn can be retried through a collection.
- [ ] Community tools (e.g. surveys, forum, chat). Unclear how, exactly, but it definitely involves users creating accounts and having a profile.
