### ISSUE TITLE
Outreach / messaging / community engagement features tracking issue

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-data-rust#629]
I'd like to explore what it would take for Atomic-Server to be usable as a back-end for a community platform.
That would be one possible USP that Atomic-Server might be able to excel at and have an advantage over other headless CMS tools.
At this moment, I don't think it's likely that Atomic-Server will get many community features, as it will probably be a really big investment, so keep that in mind.
This is just a list to keep track of the features that will be required for this type of app.

- [ ] Email support #276 
  - [ ] Write and design e-mail, send to some group (i.e. mailchimp, but more basic)
- [ ] Groups #476 
- [ ] Table to view / edit users #538 
- [x] Group chat #373 
- [x] Basic CMS features (article creation / editing, menu structure)
- [ ] Browser notifications #77 
- [ ] Surveys (custom form with fields, anonymous entry)
